// components/sidebar/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucPageBuilderSidebarProps } from '../interfaces'

import { getWidgetShortLabel, widgetIcon } from '../../utils/widgets'

import './_index.scss'

export function NucPageBuilderSidebar({
  pages,
  selectedPageId,
  filteredWidgets,
  groupedWidgets,
  collapsedGroups,
  widgetSearch,
  widgetSources,
  activeWidgetSource,
  onCreatePage,
  onLoadPage,
  onDeletePage,
  onWidgetSearchChange,
  onWidgetSourceChange,
  onToggleGroup,
  onWidgetDragStart,
  onAddWidget,
}: NucPageBuilderSidebarProps): JSX.Element {
  return (
    <aside className="pb-sidebar pb-panel">
      <div className="pb-header-row">
        <h3>Pages</h3>
        <button type="button" className="pb-btn" onClick={onCreatePage}>
          + New
        </button>
      </div>
      <ul className="pb-pages-list">
        {pages.map((page) => (
          <li key={page.id}>
            <div
              className={`pb-page-item${selectedPageId === page.id ? ' active' : ''}`}
              onClick={() => onLoadPage(page.id)}
              onKeyDown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') {
                  onLoadPage(page.id)
                }
              }}
              role="button"
              tabIndex={0}
            >
              <span>{page.title}</span>
              <div className="pb-page-item-right">
                <small>{page.status}</small>
                <button
                  type="button"
                  className="pb-page-delete"
                  title="Delete page"
                  onClick={(event) => {
                    event.stopPropagation()
                    onDeletePage(page.id)
                  }}
                >
                  ✕
                </button>
              </div>
            </div>
          </li>
        ))}
      </ul>

      <div className="pb-header-row pb-widget-header">
        <h3>Widgets</h3>
        <span className="pb-chip">{filteredWidgets.length}</span>
      </div>

      <div className="pb-widget-search-row">
        <svg
          className="pb-search-icon"
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden
        >
          <circle cx="11" cy="11" r="8" />
          <path d="m21 21-4.3-4.3" />
        </svg>
        <input
          value={widgetSearch}
          className="pb-input pb-input-search"
          placeholder="Search widgets..."
          onChange={(event) => onWidgetSearchChange(event.target.value)}
        />
      </div>

      <div className="pb-source-tabs">
        {widgetSources.map((source) => (
          <button
            key={source}
            type="button"
            className={`pb-source-tab${activeWidgetSource === source ? ' active' : ''}`}
            onClick={() => onWidgetSourceChange(source)}
          >
            {source}
          </button>
        ))}
      </div>

      <div className="pb-widget-groups">
        {groupedWidgets.map((group) => (
          <div key={group.key}>
            <button
              type="button"
              className={`pb-group-header${collapsedGroups.has(group.key) ? ' collapsed' : ''}`}
              onClick={() => onToggleGroup(group.key)}
            >
              <span className="pb-group-header-left">
                <span className="pb-group-icon">{group.icon}</span>
                <span className="pb-group-label">{group.label}</span>
              </span>
              <span className="pb-group-header-right">
                <span className="pb-chip pb-chip-sm">
                  {group.widgets.length}
                </span>
                <span className="pb-group-chevron">›</span>
              </span>
            </button>
            {!collapsedGroups.has(group.key) ? (
              <div
                className={`pb-widget-grid${group.key === 'Native' ? ' pb-widget-grid-2col' : ''}`}
              >
                {group.widgets.map((widget) => (
                  <button
                    key={widget.key}
                    type="button"
                    draggable
                    className={`pb-widget-card${widget.source === 'native' ? ' pb-widget-card-native' : ''}`}
                    title={widget.label}
                    onDragStart={() => onWidgetDragStart(widget.key)}
                    onClick={() => onAddWidget(widget.key)}
                  >
                    <span className="pb-widget-card-icon">
                      {widgetIcon(widget)}
                    </span>
                    <span className="pb-widget-card-label">
                      {getWidgetShortLabel(widget)}
                    </span>
                  </button>
                ))}
              </div>
            ) : null}
          </div>
        ))}
        {filteredWidgets.length === 0 ? (
          <p className="pb-empty-small">No widgets found for this filter.</p>
        ) : null}
      </div>
    </aside>
  )
}

export default NucPageBuilderSidebar

// components/sidebar/index.vue
<template>
  <aside class="pb-sidebar pb-panel">
    <div class="pb-header-row">
      <h3>Pages</h3>
      <button class="pb-btn" @click="emit('create-page')">+ New</button>
    </div>
    <ul class="pb-pages-list">
      <li v-for="page in pages" :key="page.id">
        <div
          class="pb-page-item"
          :class="{ active: selectedPageId === page.id }"
          @click="emit('load-page', page.id)"
        >
          <span>{{ page.title }}</span>
          <div class="pb-page-item-right">
            <small>{{ page.status }}</small>
            <button
              class="pb-page-delete"
              title="Delete page"
              @click.stop="emit('delete-page', page.id)"
            >
              ✕
            </button>
          </div>
        </div>
      </li>
    </ul>

    <div class="pb-header-row pb-widget-header">
      <h3>Widgets</h3>
      <span class="pb-chip">{{ filteredWidgets.length }}</span>
    </div>

    <div class="pb-widget-search-row">
      <svg
        class="pb-search-icon"
        xmlns="http://www.w3.org/2000/svg"
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="11" cy="11" r="8" />
        <path d="m21 21-4.3-4.3" />
      </svg>
      <input
        :value="widgetSearch"
        class="pb-input pb-input-search"
        placeholder="Search widgets..."
        @input="emit('update:widget-search', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="pb-source-tabs">
      <button
        v-for="source in widgetSources"
        :key="source"
        class="pb-source-tab"
        :class="{ active: activeWidgetSource === source }"
        @click="emit('update:widget-source', source)"
      >
        {{ source }}
      </button>
    </div>

    <div class="pb-widget-groups">
      <template v-for="group in groupedWidgets" :key="group.key">
        <button
          class="pb-group-header"
          :class="{ collapsed: collapsedGroups.has(group.key) }"
          @click="emit('toggle-group', group.key)"
        >
          <span class="pb-group-header-left">
            <span class="pb-group-icon">{{ group.icon }}</span>
            <span class="pb-group-label">{{ group.label }}</span>
          </span>
          <span class="pb-group-header-right">
            <span class="pb-chip pb-chip-sm">{{ group.widgets.length }}</span>
            <span class="pb-group-chevron">›</span>
          </span>
        </button>
        <div
          v-if="!collapsedGroups.has(group.key)"
          class="pb-widget-grid"
          :class="{ 'pb-widget-grid-2col': group.key === 'Native' }"
        >
          <button
            v-for="widget in group.widgets"
            :key="widget.key"
            draggable="true"
            class="pb-widget-card"
            :class="{ 'pb-widget-card-native': widget.source === 'native' }"
            :title="widget.label"
            @dragstart="emit('widget-drag-start', widget.key)"
            @click="emit('add-widget', widget.key)"
          >
            <span class="pb-widget-card-icon">{{ widgetIcon(widget) }}</span>
            <span class="pb-widget-card-label">
              {{ getWidgetShortLabel(widget) }}
            </span>
          </button>
        </div>
      </template>
      <p v-if="filteredWidgets.length === 0" class="pb-empty-small">
        No widgets found for this filter.
      </p>
    </div>
  </aside>
</template>

<script setup lang="ts">
import type {
  PageBuilderPageInterface,
  PageBuilderWidgetDefinitionInterface,
  WidgetGroup,
} from '../../types/interfaces'
import type { PageBuilderWidgetSourceFilter } from '../../types/variables'
import { getWidgetShortLabel, widgetIcon } from '../../utils/widgets'

interface Props {
  pages: PageBuilderPageInterface[]
  selectedPageId: number | null
  filteredWidgets: PageBuilderWidgetDefinitionInterface[]
  groupedWidgets: WidgetGroup[]
  collapsedGroups: Set<string>
  widgetSearch: string
  widgetSources: PageBuilderWidgetSourceFilter[]
  activeWidgetSource: PageBuilderWidgetSourceFilter
}

defineProps<Props>()

const emit = defineEmits<{
  'create-page': []
  'load-page': [pageId: number]
  'delete-page': [pageId: number]
  'update:widget-search': [value: string]
  'update:widget-source': [value: PageBuilderWidgetSourceFilter]
  'toggle-group': [key: string]
  'widget-drag-start': [widgetKey: string]
  'add-widget': [widgetKey: string]
}>()
</script>

<style lang="scss">
@import 'index';
</style>
