// index.tsx
'use client'

import type { JSX } from 'react'

import { NucPageBuilderCanvas } from './components/canvas/index'
import { NucPageBuilderDialogs } from './components/dialogs/index'
import { NucPageBuilderInspector } from './components/inspector/index'
import { NucPageBuilderSidebar } from './components/sidebar/index'
import { NucPageBuilderTopbar } from './components/topbar/index'
import { usePagebuilderEditor } from './utils/use_pagebuilder_editor.react'

import './_index.scss'

export function NucPageBuilderEditor(): JSX.Element {
  const {
    activeComponentSchema,
    activeWidgetSource,
    addWidget,
    autosaveEnabled,
    collapsedGroups,
    componentJsonError,
    componentProps,
    componentPropsJson,
    confirmDeleteNodeId,
    confirmDeleteNodeName,
    confirmDeletePage,
    confirmDeletePageId,
    confirmDeletePageName,
    confirmRemoveNode,
    containerPropsSchema,
    createPage,
    draggedNodeId,
    dropTarget,
    filteredWidgets,
    form,
    getComponentProp,
    groupedWidgets,
    hasTextProp,
    inspectorTab,
    lang,
    lastSavedLabel,
    layout,
    listItems,
    loadPage,
    nativeStyleSchema,
    nodePreviewText,
    nodeWidgetDisplayName,
    onCanvasDragLeave,
    onCanvasDragOver,
    onCanvasDrop,
    onComponentPropsJsonInput,
    onContainerDragLeave,
    onContainerDragOver,
    onContainerDrop,
    onCustomStylesInput,
    onNodeDragEnd,
    onNodeDragStart,
    onNodePropChange,
    onNodeStyleChange,
    onSettingChange,
    onWidgetDragStart,
    pageCustomStyles,
    pageStyleLang,
    pages,
    publishPage,
    redo,
    removeNode,
    resolvedComponentTag,
    saveDraft,
    saveLabel,
    saveState,
    selectNode,
    selectedNode,
    selectedNodeId,
    selectedNodeIsContainer,
    selectedPageId,
    selectedPageSlug,
    setActiveWidgetSource,
    setAutosaveEnabled,
    setComponentProp,
    setComponentPropJson,
    setConfirmDeleteNodeId,
    setConfirmDeletePageId,
    setForm,
    setInspectorTab,
    setPageStyleLang,
    setWidgetSearch,
    onSetRowColumns,
    toggleGroup,
    undo,
    widgetSearch,
    widgetSources,
  } = usePagebuilderEditor()

  return (
    <section className="pb-editor">
      <NucPageBuilderTopbar
        title={form.title}
        slug={form.slug}
        lang={lang}
        saveState={saveState}
        saveLabel={saveLabel}
        lastSavedLabel={lastSavedLabel}
        autosaveEnabled={autosaveEnabled}
        selectedPageId={selectedPageId}
        selectedPageSlug={selectedPageSlug}
        onTitleChange={(title) => setForm((prev) => ({ ...prev, title }))}
        onSlugChange={(slug) => setForm((prev) => ({ ...prev, slug }))}
        onAutosaveChange={setAutosaveEnabled}
        onSave={() => void saveDraft()}
        onPublish={() => void publishPage()}
        onUndo={undo}
        onRedo={redo}
      />

      <div className="pb-layout">
        <NucPageBuilderSidebar
          pages={pages}
          selectedPageId={selectedPageId}
          filteredWidgets={filteredWidgets}
          groupedWidgets={groupedWidgets}
          collapsedGroups={collapsedGroups}
          widgetSearch={widgetSearch}
          widgetSources={widgetSources}
          activeWidgetSource={activeWidgetSource}
          onCreatePage={() => void createPage()}
          onLoadPage={(pageId) => void loadPage(pageId)}
          onDeletePage={setConfirmDeletePageId}
          onWidgetSearchChange={setWidgetSearch}
          onWidgetSourceChange={setActiveWidgetSource}
          onToggleGroup={toggleGroup}
          onWidgetDragStart={onWidgetDragStart}
          onAddWidget={addWidget}
        />

        <NucPageBuilderCanvas
          layout={layout}
          selectedNodeId={selectedNodeId}
          draggedNodeId={draggedNodeId}
          dropTarget={dropTarget}
          resolvedComponentTag={resolvedComponentTag}
          componentProps={componentProps}
          widgetDisplayName={nodeWidgetDisplayName}
          nodePreviewText={nodePreviewText}
          listItems={listItems}
          onCanvasDragOver={onCanvasDragOver}
          onCanvasDrop={onCanvasDrop}
          onCanvasDragLeave={onCanvasDragLeave}
          onNodeDragStart={onNodeDragStart}
          onNodeDragEnd={onNodeDragEnd}
          onSelectNode={selectNode}
          onRemoveNode={removeNode}
          onContainerDragOver={onContainerDragOver}
          onContainerDrop={onContainerDrop}
          onContainerDragLeave={onContainerDragLeave}
        />

        <NucPageBuilderInspector
          inspectorTab={inspectorTab}
          pageStyleLang={pageStyleLang}
          pageCustomStyles={pageCustomStyles}
          layout={layout}
          lang={lang}
          selectedPageSlug={selectedPageSlug}
          formSlug={form.slug}
          selectedNode={selectedNode}
          selectedNodeIsContainer={selectedNodeIsContainer}
          hasTextProp={hasTextProp}
          activeComponentSchema={activeComponentSchema}
          containerPropsSchema={containerPropsSchema}
          nativeStyleSchema={nativeStyleSchema}
          getComponentProp={getComponentProp}
          componentPropsJson={componentPropsJson}
          componentJsonError={componentJsonError}
          onInspectorTabChange={setInspectorTab}
          onPageStyleLangChange={setPageStyleLang}
          onSettingChange={onSettingChange}
          onNodePropChange={onNodePropChange}
          onNodeStyleChange={onNodeStyleChange}
          onCustomStylesInput={onCustomStylesInput}
          onSetComponentProp={setComponentProp}
          onSetComponentPropJson={setComponentPropJson}
          onComponentPropsJsonInput={onComponentPropsJsonInput}
          onSetRowColumns={onSetRowColumns}
        />
      </div>

      {pageCustomStyles ? <style>{pageCustomStyles}</style> : null}

      <NucPageBuilderDialogs
        confirmDeleteNodeId={confirmDeleteNodeId}
        confirmDeleteNodeName={confirmDeleteNodeName}
        confirmDeletePageId={confirmDeletePageId}
        confirmDeletePageName={confirmDeletePageName}
        onCloseNodeDialog={() => setConfirmDeleteNodeId(null)}
        onConfirmRemoveNode={confirmRemoveNode}
        onClosePageDialog={() => setConfirmDeletePageId(null)}
        onConfirmDeletePage={confirmDeletePage}
      />
    </section>
  )
}

export default NucPageBuilderEditor

// index.vue
<template>
  <section class="pb-editor">
    <nuc-page-builder-topbar
      :title="form.title"
      :slug="form.slug"
      :lang="lang"
      :save-state="saveState"
      :save-label="saveLabel"
      :last-saved-label="lastSavedLabel"
      :autosave-enabled="autosaveEnabled"
      :selected-page-id="selectedPageId"
      :selected-page-slug="selectedPageSlug"
      @update:title="form.title = $event"
      @update:slug="form.slug = $event"
      @update:autosave="autosaveEnabled = $event"
      @save="saveDraft"
      @publish="publishPage"
      @undo="undo"
      @redo="redo"
    />

    <div class="pb-layout">
      <nuc-page-builder-sidebar
        :pages="pages"
        :selected-page-id="selectedPageId"
        :filtered-widgets="filteredWidgets"
        :grouped-widgets="groupedWidgets"
        :collapsed-groups="collapsedGroups"
        :widget-search="widgetSearch"
        :widget-sources="widgetSources"
        :active-widget-source="activeWidgetSource"
        @create-page="createPage"
        @load-page="loadPage"
        @delete-page="confirmDeletePageId = $event"
        @update:widget-search="widgetSearch = $event"
        @update:widget-source="activeWidgetSource = $event"
        @toggle-group="toggleGroup"
        @widget-drag-start="onWidgetDragStart"
        @add-widget="addWidget"
      />

      <nuc-page-builder-canvas
        :layout="layout"
        :selected-node-id="selectedNodeId"
        :dragged-node-id="draggedNodeId"
        :drop-target="dropTarget"
        :resolved-component-tag="resolvedComponentTag"
        :component-props="componentProps"
        :widget-display-name="nodeWidgetDisplayName"
        :node-preview-text="nodePreviewText"
        :list-items="listItems"
        @canvas-drag-over="onCanvasDragOver"
        @canvas-drop="onCanvasDrop"
        @canvas-drag-leave="onCanvasDragLeave"
        @node-drag-start="onNodeDragStart"
        @node-drag-end="onNodeDragEnd"
        @select-node="selectNode"
        @remove-node="removeNode"
        @container-drag-over="onContainerDragOver"
        @container-drop="onContainerDrop"
        @container-drag-leave="onContainerDragLeave"
      />

      <nuc-page-builder-inspector
        :inspector-tab="inspectorTab"
        :page-style-lang="pageStyleLang"
        :page-custom-styles="pageCustomStyles"
        :layout="layout"
        :lang="lang"
        :selected-page-slug="selectedPageSlug"
        :form-slug="form.slug"
        :selected-node="selectedNode"
        :selected-node-is-container="selectedNodeIsContainer"
        :has-text-prop="hasTextProp"
        :active-component-schema="activeComponentSchema"
        :container-props-schema="containerPropsSchema"
        :native-style-schema="nativeStyleSchema"
        :get-component-prop="getComponentProp"
        :component-props-json="componentPropsJson"
        :component-json-error="componentJsonError"
        @update:inspector-tab="inspectorTab = $event"
        @update:page-style-lang="pageStyleLang = $event"
        @setting-change="onSettingChange"
        @node-prop-change="onNodePropChange"
        @node-style-change="onNodeStyleChange"
        @custom-styles-input="onCustomStylesInput"
        @set-component-prop="setComponentProp"
        @set-component-prop-json="setComponentPropJson"
        @component-props-json-input="onComponentPropsJsonInput"
        @set-row-columns="onSetRowColumns"
      />
    </div>
  </section>

  <component :is="'style'" v-if="pageCustomStyles">
    {{ pageCustomStyles }}
  </component>

  <nuc-page-builder-dialogs
    :confirm-delete-node-id="confirmDeleteNodeId"
    :confirm-delete-node-name="confirmDeleteNodeName"
    :confirm-delete-page-id="confirmDeletePageId"
    :confirm-delete-page-name="confirmDeletePageName"
    @close-node-dialog="confirmDeleteNodeId = null"
    @confirm-remove-node="confirmRemoveNode"
    @close-page-dialog="confirmDeletePageId = null"
    @confirm-delete-page="confirmDeletePage"
  />
</template>

<script setup lang="ts">
import NucPageBuilderCanvas from './components/canvas/index.vue'
import NucPageBuilderDialogs from './components/dialogs/index.vue'
import NucPageBuilderInspector from './components/inspector/index.vue'
import NucPageBuilderSidebar from './components/sidebar/index.vue'
import NucPageBuilderTopbar from './components/topbar/index.vue'
import { usePagebuilderEditor } from './utils/use_pagebuilder_editor'

const {
  activeComponentSchema,
  activeWidgetSource,
  addWidget,
  autosaveEnabled,
  collapsedGroups,
  componentJsonError,
  componentProps,
  componentPropsJson,
  confirmDeleteNodeId,
  confirmDeleteNodeName,
  confirmDeletePage,
  confirmDeletePageId,
  confirmDeletePageName,
  confirmRemoveNode,
  containerPropsSchema,
  createPage,
  draggedNodeId,
  dropTarget,
  filteredWidgets,
  form,
  getComponentProp,
  groupedWidgets,
  hasTextProp,
  inspectorTab,
  lang,
  lastSavedLabel,
  layout,
  listItems,
  loadPage,
  nativeStyleSchema,
  nodePreviewText,
  nodeWidgetDisplayName,
  onCanvasDragLeave,
  onCanvasDragOver,
  onCanvasDrop,
  onComponentPropsJsonInput,
  onContainerDragLeave,
  onContainerDragOver,
  onContainerDrop,
  onCustomStylesInput,
  onNodeDragEnd,
  onNodeDragStart,
  onNodePropChange,
  onNodeStyleChange,
  onSettingChange,
  onWidgetDragStart,
  pageCustomStyles,
  pageStyleLang,
  pages,
  publishPage,
  redo,
  removeNode,
  resolvedComponentTag,
  saveDraft,
  saveLabel,
  saveState,
  selectNode,
  selectedNode,
  selectedNodeId,
  selectedNodeIsContainer,
  selectedPageId,
  selectedPageSlug,
  setComponentProp,
  onSetRowColumns,
  setComponentPropJson,
  toggleGroup,
  undo,
  widgetSearch,
  widgetSources,
} = usePagebuilderEditor()
</script>

<style lang="scss">
@import 'index';
</style>
