// components/pagebuilder/components/Topbar/index.vue
<template>
  <header class="pb-topbar pb-panel">
    <div class="pb-topbar-left">
      <input
        :value="title"
        class="pb-input pb-input-title"
        placeholder="Page title"
        @input="emit('update:title', ($event.target as HTMLInputElement).value)"
      />
      <span class="pb-slug-prefix">/{{ lang }}/</span>
      <input
        :value="slug"
        class="pb-input pb-input-slug"
        placeholder="slug"
        @input="emit('update:slug', ($event.target as HTMLInputElement).value)"
      />
    </div>

    <div class="pb-topbar-center">
      <div class="pb-status" :class="`pb-status-${saveState}`">
        <span class="pb-status-dot" />
        {{ saveLabel }}
        <span v-if="lastSavedLabel" class="pb-status-time"> · {{ lastSavedLabel }}</span>
      </div>
    </div>

    <div class="pb-topbar-right">
      <button
        class="pb-btn pb-btn-sm"
        title="Undo (Ctrl+Z)"
        :disabled="!selectedPageId"
        @click="emit('undo')"
      >↩</button>
      <button
        class="pb-btn pb-btn-sm"
        title="Redo (Ctrl+Y)"
        :disabled="!selectedPageId"
        @click="emit('redo')"
      >↪</button>
      <span class="pb-topbar-sep" />
      <label class="pb-autosave-toggle" title="Autosave">
        <input type="checkbox" :checked="autosaveEnabled" @change="onAutosaveChange" />
        <span class="pb-autosave-label">Auto</span>
      </label>
      <span class="pb-topbar-sep" />
      <button
        class="pb-btn"
        :disabled="!selectedPageId || saveState === 'saving'"
        @click="emit('save')"
      >💾 Save</button>
      <button
        class="pb-btn pb-btn-primary"
        :disabled="!selectedPageId || saveState === 'saving'"
        @click="emit('publish')"
      >🚀 Publish</button>
      <a
        v-if="selectedPageSlug"
        class="pb-btn"
        :href="`/${lang}/${selectedPageSlug}`"
        target="_blank"
      >↗ Preview</a>
    </div>
  </header>
</template>

<script setup lang="ts">
import type { PageBuilderSaveState } from '../../types'

interface Props {
  title: string
  slug: string
  lang: string
  saveState: PageBuilderSaveState
  saveLabel: string
  lastSavedLabel: string
  autosaveEnabled: boolean
  selectedPageId: number | null
  selectedPageSlug: string | null
}

defineProps<Props>()

const emit = defineEmits<{
  'update:title': [value: string]
  'update:slug': [value: string]
  'update:autosave': [value: boolean]
  save: []
  publish: []
  undo: []
  redo: []
}>()

function onAutosaveChange(event: Event): void {
  emit('update:autosave', (event.target as HTMLInputElement).checked)
}
</script>

<style scoped lang="scss" src="./_index.scss"></style>

// components/topbar/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucPageBuilderTopbarProps } from '../interfaces'

import './_index.scss'

export function NucPageBuilderTopbar({
  title,
  slug,
  lang,
  saveState,
  saveLabel,
  lastSavedLabel,
  autosaveEnabled,
  selectedPageId,
  selectedPageSlug,
  onTitleChange,
  onSlugChange,
  onAutosaveChange,
  onSave,
  onPublish,
  onUndo,
  onRedo,
}: NucPageBuilderTopbarProps): JSX.Element {
  return (
    <header className="pb-topbar pb-panel">
      <div className="pb-topbar-left">
        <input
          value={title}
          className="pb-input pb-input-title"
          placeholder="Page title"
          onChange={(event) => onTitleChange(event.target.value)}
        />
        <span className="pb-slug-prefix">/{lang}/</span>
        <input
          value={slug}
          className="pb-input pb-input-slug"
          placeholder="slug"
          onChange={(event) => onSlugChange(event.target.value)}
        />
      </div>

      <div className="pb-topbar-center">
        <div className={`pb-status pb-status-${saveState}`}>
          <span className="pb-status-dot" />
          {saveLabel}
          {lastSavedLabel ? (
            <span className="pb-status-time"> · {lastSavedLabel}</span>
          ) : null}
        </div>
      </div>

      <div className="pb-topbar-right">
        <button
          type="button"
          className="pb-btn pb-btn-sm"
          title="Undo (Ctrl+Z)"
          disabled={!selectedPageId}
          onClick={onUndo}
        >
          ↩
        </button>
        <button
          type="button"
          className="pb-btn pb-btn-sm"
          title="Redo (Ctrl+Y)"
          disabled={!selectedPageId}
          onClick={onRedo}
        >
          ↪
        </button>
        <span className="pb-topbar-sep" />
        <label className="pb-autosave-toggle" title="Autosave">
          <input
            type="checkbox"
            checked={autosaveEnabled}
            onChange={(event) => onAutosaveChange(event.target.checked)}
          />
          <span className="pb-autosave-label">Auto</span>
        </label>
        <span className="pb-topbar-sep" />
        <button
          type="button"
          className="pb-btn"
          disabled={!selectedPageId || saveState === 'saving'}
          onClick={onSave}
        >
          💾 Save
        </button>
        <button
          type="button"
          className="pb-btn pb-btn-primary"
          disabled={!selectedPageId || saveState === 'saving'}
          onClick={onPublish}
        >
          🚀 Publish
        </button>
        {selectedPageSlug ? (
          <a
            className="pb-btn"
            href={`/${lang}/${selectedPageSlug}`}
            target="_blank"
            rel="noreferrer"
          >
            ↗ Preview
          </a>
        ) : null}
      </div>
    </header>
  )
}

export default NucPageBuilderTopbar
